name: Run tests

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: pnpm/action-setup@v4
    - run: npm pnpm install
